name: Publish .NET Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Read version from version.json
        id: version
        run: |
          VERSION=$(jq -r .version version.json)
          echo "PACKAGE_VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Pack
        run: |
          dotnet pack src/Asaas/Asaas.csproj --no-restore --configuration Release /p:PackageVersion=${{ env.PACKAGE_VERSION }}

      - name: Add GitHub Packages source
        run: dotnet nuget add source --username sfourm --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Publish to GitHub Packages
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.PACKAGE_TOKEN }} --source "github"
